version: "3.8"

services:
  makassar_management_react:
    image: thenatz1999/makassar-management-react-dev:0.0.2
    pull_policy: always
    container_name: makassar-mgmt-react
    ports:
      - "3000:3000"
    environment: {}
    command: /bin/sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
      # - /app/node_modules
    #VITE_API_URL: "https://buchinn.be/api"
    #VITE_API_IMAGES_URL: "https://buchinn.be/uploads"

  makassar_management_api:
    image: thenatz1999/makassar-management-api-dev:0.0.3
    container_name: makassar-mgmt-api
    ports:
      - "8080:8080"

    environment:
      MONGO_DBNAME: makassar-management-db-dev
      MONGO_HOST: mongoDB
      MONGO_USER: mongo-makassar
      MONGO_PASSWORD: mongo-makassar-password

    depends_on:
      - mongoDB

  mongoDB:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-makassar
      MONGO_INITDB_ROOT_PASSWORD: mongo-makassar-password
      MONGO_INITDB_DATABASE: makassar-management-db-dev
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-data:/data/db
